services:
  grafana:
    image: grafana/grafana:12.0.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks: [observability]

  prometheus:
    image: prom/prometheus:v3.4.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks: [observability]

  tempo:
    image: grafana/tempo:2.8.0
    command: ["--config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
      - "14317:14317"
    networks: [observability]

  loki:
    image: grafana/loki:3.5.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks: [observability]

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - ./promtail.yaml:/etc/promtail/promtail.yaml
      - ./logs:/app/logs
    command: -config.file=/etc/promtail/promtail.yaml
    networks: [observability]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.128.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"  # App talks to this
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks: [observability]

networks:
  observability:
